### ISSUE TITLE
Please, add check-ansible-centos-centos10-action

### ISSUE THREAD

**Issue by Jakuje** [roles-ansible/check-ansible-centos-centos9-action#3]
The CentOS 10 stream (beta) is out and it would be good to have the role running against the newer system.
I think it should be mostly change of stream9 -> stream10, but I will double-check.

**Comment by Jakuje** [comment]
The WIP branch:

https://github.com/roles-ansible/check-ansible-centos-centos9-action/compare/main...Jakuje:check-ansible-centos-centos9-action:centos10

Testing the action in willshersystems/ansible-sshd#304 now.

**Comment by Jakuje** [comment]
Sounds like this worked ok:

https://github.com/Jakuje/ansible-sshd/actions/runs/12353611673/job/34473088916

Feel free to use my branch for the new GH action (the icons were not updated though) when you will have time or let me know how I can help there.

**Comment by DO1JLR** [comment]
thanks a lot for your work @Jakuje 
https://github.com/marketplace/actions/check-ansible-centos-centos10
